config/routes.rb
Besok::Application.routes.draw do
  devise_for :users

  match "dashboard" => "dashboard#index"
  resources :tokens do
    member do
      get 'visit'
    end
  end
  

  root :to => 'welcome#index'

end

app/models/token.rb
class Token < ActiveRecord::Base
  attr_accessible :description, :name, :url, :user_id
  validates :name, :presence => true, :uniqueness => true
  validates :user_id, :presence => true
  validates :description, :presence => true
  before_validation :generate_name
  belongs_to :user
  has_many :visits
  
  def generate_name
    # So many options...
    # http://blog.logeek.fr/2009/7/2/creating-small-unique-tokens-in-ruby
    self.name = rand(36**8).to_s(36) if self.new_record?
  end
  
  def to_param
    self.name
  end
  
  def self.from_param(param)
    find_by_name!(param)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :first_name, :last_name
  # attr_accessible :title, :body
  validates :username, :presence => true
  has_many :tokens
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  attr_accessible :ip_address, :referer, :token_id, :user_agent
  belongs_to :token
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def after_sign_in_path_for(resource_or_scope)
    dashboard_path
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @tokens = Token.find_all_by_user_id(current_user.id)
  end
end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  before_filter :authenticate_user!, :except  => :visit
  
  # GET /tokens
  # GET /tokens.json
  def index
    @tokens = Token.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tokens }
    end
  end

  # GET /tokens/1
  # GET /tokens/1.json
  def show
    @token = Token.find_by_name(params[:id]) || Token.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @token }
    end
  end

  # GET /tokens/new
  # GET /tokens/new.json
  def new
    @token = Token.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @token }
    end
  end

  # GET /tokens/1/edit
  def edit
    @token = Token.find_by_name(params[:id]) || Token.find(params[:id])
  end

  # POST /tokens
  # POST /tokens.json
  def create
    # Creating the new token automatically generates a token name
    @token = Token.new(params[:token])
    
    # The user will be logged in, so autofill their ID
    @token.user = current_user
    
    respond_to do |format|
      if @token.save
        format.html { redirect_to dashboard_path, notice: 'Token was successfully created.' }
        format.json { render json: @token, status: :created, location: @token }
      else
        format.html { render action: "new" }
        format.json { render json: @token.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tokens/1
  # PUT /tokens/1.json
  def update
    @token = Token.find_by_name(params[:id]) || Token.find(params[:id])

    respond_to do |format|
      if @token.update_attributes(params[:token])
        format.html { redirect_to @token, notice: 'Token was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @token.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tokens/1
  # DELETE /tokens/1.json
  def destroy
    @token = Token.find_by_name(params[:id]) || Token.find(params[:id])
    @token.destroy

    respond_to do |format|
      format.html { redirect_to tokens_url }
      format.json { head :no_content }
    end
  end
  
  def visit
    @token = Token.find_by_name(params[:id]) || Token.find(params[:id])
    visit_params = { :ip_address => request.remote_ip || "none",
                     :user_agent => request['User-Agent'] || "none",
                     :referer => request['Referer'] || "none",
                     :token_id => @token.id }
    @token.visits << Visit.create!(visit_params)
    @token.save
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    # just load the static view
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def main_page?
    # TODO: might need to add another check in here like "and action == 'index'"
    controller.class == WelcomeController
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/_token_list.html.erb
<span>Click one to see more information</span>
<ul class="token-list">
  <% @tokens.each do |token| %>
  <a href="<%= token_path(token) %>">
    <li>
      <div class="views">
        <div><%= token.visits.count %></div>
        views
      </div>
      <span><%= token.description %></span>
    </li>
  </a>
  <% end %>
</ul>

app/views/dashboard/index.html.erb
<div class="row">
  <div class="offset2 span8">
    <h3>You have <%= pluralize(@tokens.length, 'tracking token') %>:</h3>  
    <% if @tokens.length > 0 %>
    <%= render 'token_list' %>
    <% else %>
    You don't have any tracking tokens yet. Why not <%= link_to 'create one', new_token_path %>?
    <% end%>
  </div>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Besok" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body class="<%= 'collapse' unless user_signed_in? %>">

    <% if user_signed_in? %>
    <%= render 'shared/navbar' %>
    <% end %>

    <div class="container">
      <div class="content">
        <div class="row">
          <%= flash_block %>
        </div>
        <%= yield %>
      </div><!--/content-->

      <footer>
        <p>&copy; Dave Ceddia 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "Besök", root_path, :class => 'brand' %>
      <div class="pull-right">
        <%= link_to "Sign Out", destroy_user_session_path, :class => "btn" %>
      </div>
      <div class="container nav-collapse">
        <ul class="nav">
          <li><%= link_to "Dashboard", dashboard_path  %></li>
          <li><%= link_to "New Token", new_token_path  %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/tokens/_form.html.erb
<%= form_for(@token) do |f| %>
  <% if @token.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@token.errors.count, "error") %> prohibited this token from being saved:</h2>

      <ul>
      <% @token.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>Describe your token, so you know what it's for.</p>
  <p>URL is optional, but might help you remember where you put this token ;)</p>
  <div>
    <%= f.label :description %>
    <%= f.text_field :description, :length => 60 %>
  </div>
  
  <div>
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tokens/edit.html.erb
<h1>Editing token</h1>

<%= render 'form' %>

<%= link_to 'Show', @token %> |
<%= link_to 'Back', tokens_path %>

app/views/tokens/index.html.erb
<h1>Listing tokens</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>URL</th>
  </tr>

<% @tokens.each do |token| %>
  <tr>
    <td><%= token.name %></td>
    <td><%= token.description %></td>
    <td><%= token.url %></td>
    <td><%= link_to 'Show', token %></td>
    <td><%= link_to 'Edit', edit_token_path(token) %></td>
    <td><%= link_to 'Destroy', token, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Token', new_token_path %>

app/views/tokens/new.html.erb
<h1>New token</h1>

<%= render 'form' %>

<%= link_to 'Back', tokens_path %>

app/views/tokens/show.html.erb
<p id="notice"><%= notice %></p>

<div class="show-token">
  <p>This token is named <code><%= @token.name %></code></p>

  <p>It has <span class="visit-count"><%= @token.visits.length %></span> total views.</p>

  <p>To start tracking views on a web page you control (your blog, Craigslist or Ebay ad, for instance), paste this code into the page:</p>
  <pre>&lt;img src="<%= visit_token_url(@token) %>" /&gt;</pre>
</div>
<%= link_to 'Edit', edit_token_path(@token) %> |
<%= link_to 'Back', tokens_path %>

app/views/welcome/index.html.erb
<div class="hero-unit well">
  <% if not user_signed_in? %>
    <%= link_to "Sign In", new_user_session_path, :class => "btn user-action" %>    
  <% end %>
  <%= image_tag 'besok-logo.png', :alt => 'Besok', :id => 'logo' %>
  <h1>Besök</h1>
  <span>Simple analytics and page view tracking</span>
</div>
<div class="row">
  <div class="span3">
    <h3>What is it?</h3>
    <p>Besök lets you see how much traffic your page is getting.</p>
  </div>
  
  <div class="span3">
    <h3>Why use it?</h3>
    <p>There are lots of analytics options out there. Some of them are really powerful, but can be hard to learn. Besök lets you get started quickly, and you can begin tracking visits today.</p> 
  </div>

  <div class="span3">
    <h3>How does it work?</h3>
    <ol>
      <li>Sign up (free!)</li>
      <li>Generate a page tracking token</li>
      <li>Paste the HTML code into your page</li>
    </ol>
  </div>
  
  <div class="span3">
    <h3>Sign up now!</h3>
    <p>Signing up is free! Click below.</p>
    <%= link_to "Sign Up!", new_user_registration_path, :class => "btn btn-warning btn-large" %>
  </div>
</div>